# Generated by Django 4.1.5 on 2023-01-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagemodel",
            name="second_part",
            field=models.TextField(default=None),
        ),
    ]
