# Generated by Django 4.1.5 on 2023-01-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_aboutmodel_statsmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statsmodel",
            name="about",
        ),
    ]
