# Generated by Django 4.1.5 on 2023-01-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_aboutmodel_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill",
                    models.CharField(
                        help_text="ex: Python, JS, JAVA, C++", max_length=255
                    ),
                ),
                ("percent", models.IntegerField(help_text="Projects, Awards etc..")),
            ],
        ),
        migrations.AlterField(
            model_name="aboutmodel",
            name="image",
            field=models.ImageField(default=None, upload_to="assets/img/"),
        ),
    ]
