# Generated by Django 4.1.5 on 2023-01-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_skillsmodel_alter_aboutmodel_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skillsmodel",
            name="percent",
        ),
        migrations.AddField(
            model_name="skillsmodel",
            name="percentage",
            field=models.IntegerField(
                default=0, help_text="It should be in range 0-100"
            ),
        ),
    ]
