# Generated by Django 4.1.5 on 2023-01-26 18:58

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_remove_skillsmodel_percent_skillsmodel_percentage"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="ex: Football, Pocker, Chess, Coding", max_length=255
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#FF0000", image_field=None, max_length=18, samples=None
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        help_text="choose icons from https://remixicon.com/",
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
