# Generated by Django 4.1.5 on 2023-01-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_interestmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestimonialModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(default="Unknown", max_length=255)),
                ("image", models.ImageField(default=None, upload_to="assets/img/")),
                ("position", models.CharField(default=None, max_length=255)),
                ("text", models.TextField()),
            ],
        ),
    ]
